// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkflowApi.Infrastructure.Data;

#nullable disable

namespace WorkflowApi.Infrastructure.Migrations
{
    [DbContext(typeof(WorkflowApiDbContext))]
    [Migration("20251127055320_InitailCreate")]
    partial class InitailCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkflowApi.Domain.Entities.WorkflowRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType")
                        .HasDatabaseName("IX_WorkflowRoutes_DocumentType");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_WorkflowRoutes_IsActive");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_WorkflowRoutes_IsDeleted");

                    b.HasIndex("RouteName", "DocumentType")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkflowRoutes_RouteName_DocumentType")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("WorkflowRoutes", (string)null);
                });

            modelBuilder.Entity("WorkflowApi.Domain.Entities.WorkflowStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowReturn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("CompletionRule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExecutionMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsFinalStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NextStepCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParallelGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ReturnBehavior")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<int?>("ReturnStepId")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("int");

                    b.Property<string>("StepName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsFinalStep")
                        .HasDatabaseName("IX_WorkflowSteps_IsFinalStep");

                    b.HasIndex("ParallelGroupId")
                        .HasDatabaseName("IX_WorkflowSteps_ParallelGroupId");

                    b.HasIndex("ReturnStepId");

                    b.HasIndex("RouteId")
                        .HasDatabaseName("IX_WorkflowSteps_RouteId");

                    b.HasIndex("RouteId", "SequenceNo")
                        .HasDatabaseName("IX_WorkflowSteps_RouteId_SequenceNo");

                    b.ToTable("WorkflowSteps", (string)null);
                });

            modelBuilder.Entity("WorkflowApi.Domain.Entities.WorkflowStepAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentType")
                        .HasColumnType("int");

                    b.Property<string>("NId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OUResolutionMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<int?>("OrganizationalUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("StepId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentType")
                        .HasDatabaseName("IX_WorkflowStepAssignments_AssignmentType");

                    b.HasIndex("NId")
                        .HasDatabaseName("IX_WorkflowStepAssignments_NId");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("IX_WorkflowStepAssignments_PositionId");

                    b.HasIndex("StepId")
                        .HasDatabaseName("IX_WorkflowStepAssignments_StepId");

                    b.ToTable("WorkflowStepAssignments", (string)null);
                });

            modelBuilder.Entity("WorkflowApi.Domain.Entities.WorkflowStep", b =>
                {
                    b.HasOne("WorkflowApi.Domain.Entities.WorkflowStep", "ReturnStep")
                        .WithMany()
                        .HasForeignKey("ReturnStepId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WorkflowApi.Domain.Entities.WorkflowRoute", "Route")
                        .WithMany("Steps")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReturnStep");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("WorkflowApi.Domain.Entities.WorkflowStepAssignment", b =>
                {
                    b.HasOne("WorkflowApi.Domain.Entities.WorkflowStep", "Step")
                        .WithMany("Assignments")
                        .HasForeignKey("StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Step");
                });

            modelBuilder.Entity("WorkflowApi.Domain.Entities.WorkflowRoute", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("WorkflowApi.Domain.Entities.WorkflowStep", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
